name = "KnightCraft5"
author = "umceko"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f462c86dc4e16d87ae4fb88f9c44c99a4edb31a7361e316fadbd8f2023758f7a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
