name = "KnightCraft5"
author = "umceko"
version = "5.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb8cdbcd2c664fc57897d676cefe156b8d51dbe7f744dbe665e6c990692667fd"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
