#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Jul 29 01:10:37 TRT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=
enableShaders=false
